module Texts.Ludvig exposing (texts)


texts : List String
texts =
    [ "Artistic research is a more narrow term than art.                                                                                                                                                           Artistic research encompasses a subset of artistic activities.                                                                                                                                                                                      Artistic research does not      require aesthetic adaptation,           but certain aesthetic approaches are    more compatible with the superficial traits of traditional modes of research.                                                                                                                                                                   The idea of Artistic Research is a childof its time, it could not have existed  50 years ago, and it might not exist 50 years from now."
    , "                                                               Artistic Research evokes directionality,                              spatial relationships with art. Such as                   through                    towards                      in                 about                      .                                                                                                                                  Perhaps thinkingin terms of directions and becomings    is more generative than trying to pin-  point a position on the map where       artistic research is supposed to be     located.                                                                                                                                                                                                                                                                                                                                           "
    ]

