module Texts.Ludvig exposing (texts)

import Texts


texts : List Texts.EntryWithIndex
texts =
    [ ( 0, Texts.noNl "                                                                                                                                                                                                                                                                                        Artistic work can be understood as sequences of trans-formations                        trans-lations                           trans-mutations                         trans-positions                            re-combinations                         re-formulations                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           " )
    , ( 1, Texts.noNl "" ) 
    , ( 2, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    curiosity                               to                                      work                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           " ) 
    , ( 3, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    action                                  to                                      thought                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " ) 
    , ( 4, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    experience                              to                                      knowledge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      " ) 
    , ( 5, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    one form of knowledge                   to                                      another form of knowledge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      " ) 
    , ( 6, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    one form                                to                                      another form                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   " ) 
    , ( 7, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    one expression                          to                                      another expression                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             " ) 
    , ( 8, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    intuition                               to                                      exploration                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    " ) 
    , ( 9, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    concern                                 to                                      inquiry                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        " ) 
    , ( 10, Texts.noNl "                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        from                                    one person                              to                                      another person                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 " ) 
    , ( 11, Texts.noNl "" ) 
    , ( 12, Texts.noNl "" ) 
    , ( 13, Texts.noNl "" ) 
    ]



