
For testing locally, directory with audiofiles should be in the 'audio'
folder in the in 'files' directory. This directory will be ignored by
git. 

Use the sync.sh script to synchronize with the server. The script uses rsync:
it first downloads the new files from the server and then synchronizes
the local 'files' directory with the server.


Audio files in each 'page*' directory should be named 
#+BEGIN_SRC
david.mp3
gerhard.mp3
luc.mp3
ludvig.mp3
#+END_SRC

the js function:

#+BEGIN_SRC
bufferLoader.loadAll( );
#+END_SRC

loads all files in mp3 format

while the js function:

#+BEGIN_SRC
bufferLoader.sendAmps(2, [0.9, 0.1, .... 0.0]);
#+END_SRC

sends an array of amplitude values for all files over all pages
associated with index 2. The array length should be equal to the
number of pages (4 in this testingv ersion).

The js function

#+BEGIN_SRC
bufferLoader.sendPan(2, -0.4);
#+END_SRC

sets the panorama for index 2. Panorama values should range from -1.0 (left),
to 1.0 (right).

test locally with:

#+BEGIN_SRC
$ http-server .
#+END_SRC

