
For testing locally, directory with audiofiles should be in the 'audio'
folder in the in 'files' directory. This directory will be ignored by
git. 

The directory with all audio files lies in a git repository on a
server. To clone the git repository:

#+BEGIN_SRC
git clone git@116.202.8.138:/home/git/towards_files.git
#+END_SRC

this will create the directory towards_files, containing all the page
directories with the audio files. In order to make this work locally
you need to link this directory into the towards/audio/ folder: the
linked directory should be names "files" e.g on
my system:

#+BEGIN_SRC
ln -s ../../towards_files ./files
#+END_SRC

As with the towards repository, the git repository containing the
audio file will be pulled every 5 minutes on the server.


The script ffmpeg_convert.sh can be used to batch convert all the
*.wav files (not containing "_" as these files are the old ones) to
*.mp3 files with give rate. For instance run:

#+BEGIN_SRC
./ffmpeg_convert.sh 192k
#+END_SRC


The js function:

#+BEGIN_SRC
bufferLoader.loadAll( );
#+END_SRC

loads all files in mp3 format

while the js function:

#+BEGIN_SRC
bufferLoader.sendAmps(2, [0.9, 0.1, .... 0.0]);
#+END_SRC

sends an array of amplitude values for all files over all pages
associated with index 2. The array length should be equal to the
number of pages (4 in this testingv ersion).

The js function

#+BEGIN_SRC
bufferLoader.sendPan(2, -0.4);
#+END_SRC

sets the panorama for index 2. Panorama values should range from -1.0 (left),
to 1.0 (right).

test locally with:

#+BEGIN_SRC
$ http-server .
#+END_SRC

