
FFLAGS = -fast -xHost

.PHONY: sound_0 sound_0_b sound_0_c sound_1 sound_text

sound_text_4:
	gfortran -fPIC -march=native -ffast-math -funroll-loops -O3 -ffree-line-length-0 sound_text_4_clean.f90 -o sound_text
